SemmDesk/Controllers/InventarioController.cs
using Data.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SemmDesk.Controllers
{
    public class InventarioController : Controller
    {
        HelpDeskEntities db = new HelpDeskEntities();

        public ActionResult Index()
        {
            return View();
        }

        //GET CREATE
        public ActionResult Create()
        {
            //var Categorias = db.CategoriaInventario.ToList();
            //ViewBag.ListaCategorias = new SelectList(Categorias,"ID","Descripcion");
            return View();
        }
        //public JsonResult getLista()
        //{
        //    db.Configuration.ProxyCreationEnabled = false;
        //    var listaInventario = db.InventarioLocal.ToList();
        //    return Json(listaInventario, JsonRequestBehavior.AllowGet);
        //}
    }
}

SemmDesk/Views/Inventario/Create.cshtml
@model Data.Entidades.InventarioLocal
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<hr />
@using (Html.BeginForm("Create","Inventario", FormMethod.Post))
{
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(model => model.CategoriaID)
            </div>
            <div class="col-md-6">
                @Html.DropDownList("CategoriaID",(SelectList)ViewBag.ListaCategorias, new {@class="form-control" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(model => model.Descripcion)
            </div>

            <div class="col-md-6">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(model => model.CodigoInventario)
            </div>

            <div class="col-md-6">
                @Html.EditorFor(model => model.CodigoInventario, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(model => model.Cantidad)
            </div>

            <div class="col-md-6">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(model => model.Ubicacion)
            </div>

            <div class="col-md-6">
                @Html.EditorFor(model => model.Ubicacion, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

    </div>    
}

SemmDesk/Views/Inventario/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table id="inventarioTable" class="table">
   <thead>

   </thead>
    <tbody>

    </tbody>
</table>

@section scripts{
    <script>
        $(document).ready(function () {
            $('#inventarioTable').DataTable({
                ajax: {
                    url: '../Inventario/getLista',
                    dataSrc : ''
                },

                columns: [
                    {
                        title: 'ID',
                        data: 'ID'
                    },

                    {
                        title: 'CATEGORIA',
                        data: 'CategoriaID'
                    },

                    {
                        title: 'DESCRIPCION',
                        data: 'Descripcion'
                    },

                    {
                        title: 'CODIGO',
                        data: 'CodigoInventario'
                    },

                    {
                        title: 'CANTIDAD',
                        data: 'Cantidad'
                    },
                    {
                        title: 'UBICACION',
                        data: 'Ubicacion'
                    }
                ]
            });
        });
    </script>
    
    }