SemmDesk/Controllers/CategoriaPrincipalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
//using Data.Contexto;
using Data.Entidades;

namespace HelpDesk.Controllers
{
    public class CategoriaPrincipalsController : Controller
    {
        private HelpDeskEntities db = new HelpDeskEntities();

        // GET: CategoriaPrincipals
        public ActionResult Index()
        {
            return View(db.CategoriaPrincipal.ToList());
        }

        // GET: CategoriaPrincipals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriaPrincipal categoriaPrincipal = db.CategoriaPrincipal.Find(id);
            if (categoriaPrincipal == null)
            {
                return HttpNotFound();
            }
            return View(categoriaPrincipal);
        }

        // GET: CategoriaPrincipals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoriaPrincipals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoriaPrincipalID,descripcion")] CategoriaPrincipal categoriaPrincipal)
        {
            if (ModelState.IsValid)
            {
                db.CategoriaPrincipal.Add(categoriaPrincipal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categoriaPrincipal);
        }
        public JsonResult lsSecundaria(int CategoriaPrincipalID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<CategoriaSecundaria> lsCategoriaSecundaria = db.CategoriaSecundaria.Where(x => x.CategoriaPrincipalID == CategoriaPrincipalID).ToList();
            return Json(lsCategoriaSecundaria, JsonRequestBehavior.AllowGet);
        }

        // GET: CategoriaPrincipals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriaPrincipal categoriaPrincipal = db.CategoriaPrincipal.Find(id);
            if (categoriaPrincipal == null)
            {
                return HttpNotFound();
            }
            return View(categoriaPrincipal);
        }

        // POST: CategoriaPrincipals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoriaPrincipalID,descripcion")] CategoriaPrincipal categoriaPrincipal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoriaPrincipal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categoriaPrincipal);
        }

        // GET: CategoriaPrincipals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriaPrincipal categoriaPrincipal = db.CategoriaPrincipal.Find(id);
            if (categoriaPrincipal == null)
            {
                return HttpNotFound();
            }
            return View(categoriaPrincipal);
        }

        // POST: CategoriaPrincipals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CategoriaPrincipal categoriaPrincipal = db.CategoriaPrincipal.Find(id);
            db.CategoriaPrincipal.Remove(categoriaPrincipal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SemmDesk/Controllers/CategoriaSecundariasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
//using Data.Contexto;
using Data.Entidades;

namespace HelpDesk.Controllers
{
    public class CategoriaSecundariasController : Controller
    {
        private HelpDeskEntities db = new HelpDeskEntities();

        // GET: CategoriaSecundarias
        public ActionResult Index()
        {
            return View(db.CategoriaSecundaria.ToList());
        }

        // GET: CategoriaSecundarias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriaSecundaria categoriaSecundaria = db.CategoriaSecundaria.Find(id);
            if (categoriaSecundaria == null)
            {
                return HttpNotFound();
            }
            return View(categoriaSecundaria);
        }

        // GET: CategoriaSecundarias/Create
        public ActionResult Create()
        {
            CategoriaPrincipal categoriaPrincipal = new CategoriaPrincipal();
            var lsCategoriaPrincipal = db.CategoriaPrincipal.ToList();
            ViewBag.CategoriaPrincipal = new SelectList(lsCategoriaPrincipal, "CategoriaPrincipalID", "Descripcion", categoriaPrincipal.CategoriaPrincipalID);
            return View();
        }

        // POST: CategoriaSecundarias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoriaSecundariaID,Descripcion,CategoriaPrincipalID")] CategoriaSecundaria categoriaSecundaria)
        {
            if (ModelState.IsValid)
            {
                db.CategoriaSecundaria.Add(categoriaSecundaria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categoriaSecundaria);
        }

        // GET: CategoriaSecundarias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriaSecundaria categoriaSecundaria = db.CategoriaSecundaria.Find(id);
            if (categoriaSecundaria == null)
            {
                return HttpNotFound();
            }
            var lsCategoriaPrincipal = db.CategoriaPrincipal.ToList();
            lsCategoriaPrincipal.Add(new CategoriaPrincipal {CategoriaPrincipalID = 0, descripcion = "[..Escoja una Categoria..]" } );
            lsCategoriaPrincipal = lsCategoriaPrincipal.OrderBy(l => l.descripcion).ToList();
            ViewBag.CategoriaPrincipalID = new SelectList(lsCategoriaPrincipal, "CategoriaPrincipalID", "Descripcion", categoriaSecundaria.CategoriaPrincipalID);
            Session["valor"] = categoriaSecundaria.CategoriaPrincipal.descripcion;
            return View(categoriaSecundaria);
        }

        // POST: CategoriaSecundarias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoriaSecundariaID,Descripcion,CategoriaPrincipalID")] CategoriaSecundaria categoriaSecundaria)
        {
            var lsCategoriaPrincipal = db.CategoriaPrincipal.ToList();
            lsCategoriaPrincipal.Add(new CategoriaPrincipal { CategoriaPrincipalID = 0, descripcion = "[..Escoja una Categoria..]" });
            lsCategoriaPrincipal = lsCategoriaPrincipal.OrderBy(l => l.descripcion).ToList();
            ViewBag.CategoriaPrincipalID = new SelectList(lsCategoriaPrincipal, "CategoriaPrincipalID", "Descripcion", categoriaSecundaria.CategoriaPrincipalID);
            if (ModelState.IsValid)
            {
                if (categoriaSecundaria.CategoriaPrincipalID == 0)
                {
                    return View(categoriaSecundaria);
                }
                db.Entry(categoriaSecundaria).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categoriaSecundaria);
        }

        // GET: CategoriaSecundarias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriaSecundaria categoriaSecundaria = db.CategoriaSecundaria.Find(id);
            if (categoriaSecundaria == null)
            {
                return HttpNotFound();
            }
            return View(categoriaSecundaria);
        }

        // POST: CategoriaSecundarias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CategoriaSecundaria categoriaSecundaria = db.CategoriaSecundaria.Find(id);
            db.CategoriaSecundaria.Remove(categoriaSecundaria);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SemmDesk/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    @*<meta http-equiv="refresh" content="40" />*@ @*Para refrescar la pagina x tiempo si asi lo decide el encargado*@
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="icon" href="@Url.Content("~/content/favicon.ico")" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <link href="~/Content/metisMenu.min.css" rel="stylesheet" />
    <script type='text/javascript' src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body> 

    <div class="navbar  navbar-fixed-top col-md-12 col-lg-push-8 col-xs-12" style="background-color:#1EA6FF" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar" style="background-color:#006700"></span>
                    <span class="icon-bar" style="background-color:#006700"></span>
                    <span class="icon-bar" style="background-color:#006700"></span>
                </button>
                @Html.ActionLink("SemmDesk", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @style = "color:#006700" })
            </div>

            <div class="navbar-collapse collapse container" role="navigation">
                <ul class="nav navbar-nav">

                    @if (User.IsInRole("1"))
                     {
                        <li>@Html.ActionLink("Incidencias", "Index", "Incidencias", null, new { @style = "color:#006700" })</li>
                        <li>@Html.ActionLink("Reportar", "Create", "Incidencias", null, new { @style = "color:#006700" })</li>
                        @*<li>@Html.ActionLink("Reportes", "Index", "Reportes", null, new { @style = "color:#006700" })</li>*@
                        @*<li>@Html.ActionLink("Categorias", "Index", "CategoriaPrincipals", null, new { @style = "color:#006700", @class = "dropdown-item" })</li>@
                        <li>@Html.ActionLink("Sub-categorias", "Index", "CategoriaSecundarias", null, new { @style = "color:#006700" })</li>*@
                        <li>
                            <a href="~/Reportes/Index" style="color:#006700;">Reportes</a>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" style="color:#006700" aria-expanded="false">
                                Categorias
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li >@Html.ActionLink("Principales", "Index", "CategoriaPrincipals")</li>
                                <li>@Html.ActionLink("Secundarias", "Index", "CategoriaSecundarias")</li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home", null, new { @style = "color:#006700" })</li>

               
                     }
                        else
                        {
                        <li>@Html.ActionLink("Incidencias", "Index", "Incidencias", null, new { @style = "color:#006700" })</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home", null, new { @style = "color:#006700" })</li>
                        }
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="navbar-fixed-bottom">          
           
                <p>&copy; @DateTime.Now.Year - HDSSD Developers</p>
            
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*<script src="~/Scripts/jquery-3.3.1.min.js"></script>*@
    @*<script src="~/App/app.js"></script>
    <script src="~/Scripts/angular.min.js"></script>*@


    @RenderSection("scripts", required: false)
</body>
</html>

SemmDesk/Views/Shared/_Menu.cshtml
@model IEnumerable<Data.Entidades.Menu>
@{
    ViewBag.Title = "Home Page";
}

<div>
    @foreach (var item in Model)
    {
        if (User.IsInRole("3"))
        {



        }
        else
        {
            <li>@Html.ActionLink(item.NombreMenu, item.Action, item.Controller)</li>
        }
    }

</div>