SemmDesk/Controllers/IncidenciasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
//using Data.Contexto;
using Data.Entidades;
using Newtonsoft.Json;

namespace HelpDesk.Controllers
{
    [Authorize]
    public class IncidenciasController : Controller
    {
        private HelpDeskEntities db = new HelpDeskEntities();
        //private HelpDeskEntities1 db2 = new HelpDeskEntities1();
        private CategoriaPrincipal cPrincipal = new CategoriaPrincipal();
        //private Usuario usuario = new Usuario();
        private Incidencia incidencia = new Incidencia();

        // GET: Incidencias
        public ActionResult Index(string parametro = "")
        {
            var lsTecnicos = db.Tecnicos.ToList();

            lsTecnicos = lsTecnicos.OrderBy(c => c.NombreTecnico).ToList();
            ViewBag.TecnicoID = new SelectList(lsTecnicos, "NombreTecnico", "NombreTecnico");

            var lista = db.Incidencia.ToList();

            #region ViewBags para conteo
            //Contando las incidencias TotalIncidencias
            ViewBag.TotalIncidencias =
                 lista.Count();

            //Contando las incidencias abiertas
            ViewBag.Abiertas =
                 (from incidencia in db.Incidencia
                  where incidencia.EstadoIncidenciaID == 1
                  select incidencia)
                 .Count();

            //Contando las incidencias cerradas
            ViewBag.Cerradas =
                 (from incidencia in db.Incidencia
                  where incidencia.EstadoIncidenciaID == 2
                  select incidencia)
                 .Count();


            //Contando las incidencias reasignadas

            ViewBag.Reasignadas =
                 (from incidencia in db.Incidencia
                  where incidencia.EstadoIncidenciaID == 3
                  select incidencia)
                 .Count();


            //Contando las incidencias retrasadas

            ViewBag.Retrasadas =
                 (from incidencia in db.Incidencia
                  where incidencia.EstadoIncidenciaID == 4
                  select incidencia)
                 .Count();

            ViewBag.Prioridad =
                 (from incidencia in db.Incidencia
                  where incidencia.PrioridadID == 1
                  select incidencia)
                 .Count();

            lista.Reverse();
            ViewBag.CantidadIncidencias = lista.Count();
            #endregion
            //Para filtrar por tecnicos en la lista de Incidencias
            if (parametro == "")
            {
                //Si el usuario es Administrador podra ver todas las incidencias
                if (User.IsInRole("1"))
                {
                    int _count = db.Incidencia.ToList().Count;

                    //Estoy utilizando GetRange de la lista para cuando sean muchas solo mostrar una cantidad especifica en el index
                    lista = db.Incidencia.ToList().OrderByDescending(o => o.Fecha).ThenBy(o => o.EstadoIncidenciaID).ToList().GetRange(0, _count);
                    //var stored = db2.selectVUsuarios().ToList();

                    return View("IndexAdmin",lista);
                }
                if (User.IsInRole("2"))
                {

                    var listaTecnicos = lista.Where(x => x.Tecnicos.Identificador == User.Identity.Name.Trim()).ToList();
                    return View("IndexTecnicos",listaTecnicos);
                }
                //De lo contrario solo vera las incidencias del usuairo identificado
                else
                {
                    lista = db.Incidencia.Where(x => x.UsuarioNombre == User.Identity.Name).ToList().OrderByDescending(o => o.Fecha).ThenBy(o => o.EstadoIncidenciaID).ToList();

                    //lista = db.Incidencia.Where(x => x.Usuario.UsuarioNombre == User.Identity.Name).ToList().OrderByDescending(o => o.Fecha).ThenBy(o => o.EstadoIncidenciaID).ToList();

                    return View(lista);
                }
            }
            else if (parametro != "")
            {

                lista = db.Incidencia.Where(x => x.Tecnicos.NombreTecnico == parametro).OrderBy(l => l.EstadoIncidenciaID).ToList();
            }
           
            return View(lista.ToList());
        }

        // GET: Incidencias/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Incidencia incidencia = db.Incidencia.Find(id);
            if (incidencia == null)
            {
                return HttpNotFound();
            }
            if (User.IsInRole("1") || User.IsInRole("2"))
               return View("DetailsTecnicos", incidencia);
            return View(incidencia);
        }

        // GET: Incidencias/Create
        public ActionResult Create()
        {
            Incidencia incidencia = new Incidencia();

            //Creo ViewBags para mandar el nombre de departamento y usuario que estan identicado a la vista

            #region Usuarios y Departamento de la otra BD
            //  var qDepartamento = (from u in db.Usuario
            //                       join d in db.Departamentos
            //                       on u.DepartamentoID equals d.DepartamentoID
            //                       where u.UsuarioNombre == User.Identity.Name.ToString()
            //                       select d.Descripcion
            //);

            //  var qUsuario = (from u in db.Usuario
            //                  join d in db.Departamentos
            //                  on u.DepartamentoID equals d.DepartamentoID
            //                  where u.UsuarioNombre == User.Identity.Name.ToString()
            //                  select u.UsuarioNombre
            //     );
            #endregion

            Departamentos departamentos = new Departamentos();
            var usuarios = db.selectVUsuarios();
            var usuario = db.selectVUsuarios().FirstOrDefault(u => u.usuario == User.Identity.Name);
            var nombreUsuario = usuario.FullName.Trim();
            var departamento = db.selectVUsuarios().Where(d => d.FullName == nombreUsuario);
            ViewBag.nombreUsuario = nombreUsuario;
            ViewBag.nombreDepartamento = departamento.ToString();



            // Creo ViewBags para mandar listas a la vista de crear
            #region ViewBags
            //Para organizar la lista del ViewBag de la Categoria Principal
            var lista = db.CategoriaPrincipal.ToList();
            lista.Add(new CategoriaPrincipal { CategoriaPrincipalID = 0, descripcion = "[..Seleccione una Categoria..]" });
            lista = lista.OrderBy(c => c.descripcion).ToList();
            ViewBag.CategoriaPrincipalID = new SelectList(lista, "CategoriaPrincipalID", "descripcion", incidencia.CategoriaPrincipalID);

            //Para organizar la lista del ViewBag para Tecnicos
            var lsTecnicos = db.Tecnicos.ToList();
            lsTecnicos.Add(new Tecnicos { TecnicoID = 0, NombreTecnico = "[..Seleccione un Tecnico..]" });
            lsTecnicos = lsTecnicos.OrderBy(c => c.NombreTecnico).ToList();
            ViewBag.TecnicoID = new SelectList(lsTecnicos, "TecnicoID", "NombreTecnico", incidencia.TecnicoID);

            //Para organizar la lista del ViewBag para Departamentos
            var lsDepartamentos = db.Departamentos.ToList();
            lsDepartamentos.Add(new Departamentos { DepartamentoID = 0, Descripcion = "[..Seleccione un Departamento..]" });
            lsDepartamentos = lsDepartamentos.OrderBy(c => c.Descripcion).ToList();
            ViewBag.DepartamentoID = new SelectList(lsDepartamentos, "DepartamentoID", "Descripcion", incidencia.DepartamentoID);

            //  ViewBag.CategoriaSecundariaID = new SelectList(db.CategoriaSecundaria, "CategoriaSecundariaID", "Descripcion");
            ViewBag.EstadoIncidenciaID = new SelectList(db.EstadoIncidencia, "EstadoIncidenciaId", "Descripcion");
            ViewBag.PrioridadID = new SelectList(db.Prioridad, "PrioridadID", "Descripcion");
            ViewBag.UsuarioID = new SelectList(db.Usuario, "UsuarioID", "UsuarioNombre");

            #endregion
            return View();
        }

        // POST: Incidencias/Create
        
        [HttpPost]     
        public ActionResult Create(Incidencia incidencia)
        {
            //Como este enviando el DepartamentoID y el UsuarioID como 0 desde la vista; hago un query para darle el 
            //valor segun el usuario identidificado
            #region
            var usuario = db.selectVUsuarios().Where(u => u.usuario == User.Identity.Name).ToList();

            //var qUsuarioID = db.selectVUsuarios().Where(u => u.usuario == User.Identity.Name).ToList();
            
            #endregion

            if (ModelState.IsValid)
            {
                if (incidencia.DepartamentoID == 0)
                {
                    incidencia.DepartamentoID =(int)usuario.FirstOrDefault().departam;
                    incidencia.UsuarioID = usuario.FirstOrDefault().codigo; 
                }

                incidencia.Fecha = DateTime.Now;
                if (incidencia.PrioridadID == null)
                {
                    incidencia.PrioridadID = 2;
                }
                if (incidencia.TecnicoID == null || incidencia.TecnicoID == 0)
                {
                    incidencia.TecnicoID = 3;
                }
                if (incidencia.EstadoIncidenciaID == null)
                {
                    incidencia.EstadoIncidenciaID = 1;
                }

                incidencia.UsuarioNombre = usuario.FirstOrDefault().usuario.Trim();
               
                db.Incidencia.Add(incidencia);
                db.SaveChanges();

SemmDesk/Views/Incidencias/Create.cshtml
@model Data.Entidades.Incidencia

@{
    ViewBag.Title = "Creacion Incidencias";
}

<hr />

<div class="container" style="background-color:lightgreen; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size:12px">
    <div class="col-md-6">
        <h5> Departamento:  @Html.Label((string)ViewBag.nombreDepartamento)</h5>
    </div>
    <div class="col-md-6">
        <h5>Nombre: @Html.LabelFor(user => user.UsuarioNombre, (string)ViewBag.nombreUsuario)</h5>
    </div>
</div>

@using (Html.BeginForm("Create","Incidencias",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <hr />
    <br />

    if (User.IsInRole("1"))
      {
            <div class="container" style="">
                <div class="row">
                    <br />
                    <div class="col-md-6">
                        <div class="row">
                            @*@Html.Label("Departamento", htmlAttributes: new { @class = "control-label col-md-2" })*@
                            @Html.DropDownList("DepartamentoID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.DepartamentoID, "", new { @class = "text-danger" })
                        </div>
                        <br />
                        <div class="row">
                            @Html.DropDownListFor(model => model.UsuarioID, new SelectList(" "), "--Quien llama?--", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UsuarioID, "", new { @class = "text-danger" })
                        </div><br /><br /><br /><br />

                        <div class="row">
                            @Html.DropDownList("CategoriaPrincipalID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CategoriaPrincipalID, "", new { @class = "text-danger" })

                        </div><br />
                        <div class="row">
                            @*@Html.LabelFor(model => model.CategoriaSecundariaID, "CategoriaSecundariaID", htmlAttributes: new { @class = "control-label col-md-2" })*@
                            @Html.DropDownListFor(model => model.CategoriaSecundariaID, new SelectList(" "), "[..Seleccione una Sub-Categoria..]", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CategoriaSecundariaID, "", new { @class = "text-danger" })
                        </div><br /><br /><br /><br />

                        <div class="row">
                            @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control", @style = "width: 100%; height:120px", @placeholder = "Detalle de la Incidencia" })
                            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                        </div>

                 </div>
                    
                    <div class="col-md-6">
                        <div class="row">
                            @*@Html.LabelFor(model => model.TecnicoID, htmlAttributes: new { @class = "control-label col-md-2" })*@
                            @Html.DropDownList("TecnicoID", (SelectList)ViewBag.TecnicoID, null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TecnicoID, "", new { @class = "text-danger" })

                        </div> <br />
                        <div class="row">
                            @*@Html.LabelFor(model => model.EstadoIncidenciaID, "EstadoIncidenciaID", htmlAttributes: new { @class = "control-label col-md-2" })*@
                            @Html.DropDownList("EstadoIncidenciaID", null, "Estado de la Incidencia", htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.EstadoIncidenciaID, "", new { @class = "text-danger" })
                        </div> <br /><br /><br /><br />

                        <div class="row">
                            @Html.DropDownList("PrioridadID", null, "[Prioridad de la Inciencia]", htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.PrioridadID, "", new { @class = "text-danger" })

                        </div><br /><br /><br /><br /><br /><br />
                        <div class="row">
                            @*@Html.LabelFor(model => model.ComentarioCierre, htmlAttributes: new { @class = "control-label col-md-2" })*@
                            @Html.TextAreaFor(model => model.ComentarioCierre, new { @class = "form-control", @style = "width: 100%; height:120px", @placeholder = "Comentario de Cierre" })
                            @Html.ValidationMessageFor(model => model.ComentarioCierre, "", new { @class = "text-danger" })

                        </div>
                    </div>

                </div>
             </div>
            <br />
            }
            else
            {
            <div class="container">
                @Html.HiddenFor(model => model.DepartamentoID, new { id = "DepartamentoID", name = "DepartamentoID", Value = 0 })
                @Html.HiddenFor(model => model.UsuarioID, new { id = "UsuarioID", name = "UsuarioID", Value = 0 })

                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                        
                            @Html.DropDownList("CategoriaPrincipalID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CategoriaPrincipalID, "", new { @class = "text-danger" })

                        </div><br />
                              <div class="row">
                                
                                  @Html.DropDownListFor(model => model.CategoriaSecundariaID, new SelectList(" "), "[..Seleccione una Sub-Categoria..]", new { @class = "form-control" })
                                  @Html.ValidationMessageFor(model => model.CategoriaSecundariaID, "", new { @class = "text-danger" })
                              </div><br /><br /><br /><br />
                    </div>
                    <div class="col-md-6">
                        <div class="row">
                            @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control", @style = "width: 100%; height:120px", @placeholder = "Detalle de la Incidencia" })
                            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                        </div>

                    </div>
                </div>
            </div>
            }
            <div class="container">
                <div class="row">
                    <div class="col-md-6"> </div>
                    <div class="col-md-6">                      
                        <br />                     
                        <div class="row">                           
                            <input type="submit" value="Crear incidencia" class="btn btn-primary col-md-12 "  />                         
                        </div>
                    </div><br /><br />
                </div>
            </div>            
            }
            <br />
            <div>
                @Html.ActionLink("Regresar sin guardar", "Index")
            </div>

            @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>*@
            <script src="~/Scripts/jquery-1.10.2.js"></script>
            <script>

                $(document).ready(function () {
                    $("#CategoriaPrincipalID").change(function () {
                        $.get("../Incidencias/lsSecundaria", { CategoriaPrincipalID: $("#CategoriaPrincipalID").val() }, function (data) {
                            $("#CategoriaSecundariaID").empty();
                            $.each(data, function (index, row) {
                                $("#CategoriaSecundariaID").append("<option value='" + row.CategoriaSecundariaID + "'>" + row.Descripcion + "</option>")
                            });
                        });
                    })

                    $("#DepartamentoID").change(function () {
                        $.get("../Incidencias/lsUsuarios", { DepartamentoID: $("#DepartamentoID").val() }, function (data) {
                            $("#UsuarioID").empty();
                            $.each(data, function (index, row) {
                                $("#UsuarioID").append("<option value='" + row.codigo + "'>" + row.FullName + "</option>")
                            });
                        });
                    })
                });

            </script>

SemmDesk/Views/Incidencias/Delete.cshtml
@model Data.Entidades.Incidencia

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Incidencia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TecnicoID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TecnicoID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ComentarioCierre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ComentarioCierre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCierre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCierre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UltimaModificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UltimaModificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoriaPrincipal.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoriaPrincipal.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoriaSecundaria.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoriaSecundaria.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoIncidencia.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoIncidencia.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prioridad.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prioridad.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuario.CodEmp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario.CodEmp)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SemmDesk/Views/Incidencias/Details.cshtml
@model Data.Entidades.Incidencia

@{
    ViewBag.Title = "Detalles de Incidencia";
}


<div>
    <br />
    <h4>Detalle de Incidencia</h4>
    <hr />
   
        <dl class="dl-horizontal">

            <dt>
                @Html.Label("Usuario")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UsuarioNombre)
            </dd>
            <br />
            <dt>
                @Html.Label("Fecha")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Fecha)
            </dd>
            <br />
            <dt>
                @Html.Label("Descripción")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Descripcion)
            </dd>
            <br />
            <dt>
                @Html.Label("Categoría")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CategoriaPrincipal.descripcion)
            </dd>
            <br />
            <dt>
                @Html.Label("Sub-Categoría")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CategoriaSecundaria.Descripcion)
            </dd>
            <br />
            <dt>
                @Html.Label("Estado Incidencia")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EstadoIncidencia.Descripcion)
            </dd>
            <br />
        
         
            <dt>
                @Html.Label("Comentario de Cierre")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ComentarioCierre)
            </dd>
            <br />
            <dt>
                @Html.Label("Fecha de cierre")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FechaCierre)
            </dd>
            <br />
            <dt>
                @Html.Label("Ultima Modificación")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UltimaModificacion)
            </dd>
            <br />         
            <br />


        </dl>
   
</div>
<p>  
    @Html.ActionLink("Volver atras", "Index")
</p>

SemmDesk/Views/Incidencias/DetailsTecnicos.cshtml
@model Data.Entidades.Incidencia

@{
    ViewBag.Title = "Detalles de Incidencia";
}


<div>
    <br />
    <h4>Detalle de Incidencia</h4>
    <hr />
   
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.Fecha)*@
            @Html.Label("Fecha")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <br />
        <dt>
            @*@Html.DisplayNameFor(model => model.Descripcion)*@
            @Html.Label("Descripcion")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <br />
        <dt>
            @*@Html.DisplayNameFor(model => model.TecnicoID)*@
            @Html.Label("Técnico Asignado")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tecnicos.NombreTecnico)
        </dd>
        <br />

        <dt>
            @*@Html.DisplayNameFor(model => model.CategoriaPrincipal.descripcion)*@
            @Html.Label("Categoría")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoriaPrincipal.descripcion)
        </dd>
        <br />
        <dt>
            @*@Html.DisplayNameFor(model => model.CategoriaSecundaria.Descripcion)*@
            @Html.Label("Sub-Categoría")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoriaSecundaria.Descripcion)
        </dd>
        <br />
        <dt>
            @*@Html.DisplayNameFor(model => model.EstadoIncidencia)*@
            @Html.Label("Estado Incidencia")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoIncidencia.Descripcion)
        </dd>
        <br />
        <dt>
            @*@Html.DisplayNameFor(model => model.Prioridad.Descripcion)*@
            @Html.Label("Prioridad")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prioridad.Descripcion)
        </dd>
        <br />
        <dt>
            @Html.Label("Usuario")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioNombre)
        </dd>
        <br />
        <dt>
            @Html.Label("Departamento")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departamentos.Descripcion)
        </dd>
        <br />
        <dt>
            @*@Html.DisplayNameFor(model => model.ComentarioCierre)*@
            @Html.Label("Comentario de cierre")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ComentarioCierre)
        </dd>
        <br />
        <dt>
            @*@Html.DisplayNameFor(model => model.FechaCierre)*@
            @Html.Label("Fecha de cierre")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCierre)
        </dd>
        <br />
        <dt>
            @*@Html.DisplayNameFor(model => model.UltimaModificacion)*@
            @Html.Label("Ultima Modificación")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UltimaModificacion)
        </dd>
        <br />
    </dl>
   
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.IncidenciaId }) |*@
    @Html.ActionLink("Volver atras", "Index")
</p>

SemmDesk/Views/Incidencias/Index.cshtml
@model IEnumerable<Data.Entidades.Incidencia>

@{
    ViewBag.Title = "Incidencias";
}
@*<meta http-equiv="refresh" content="5">*@
@*<h2>Listado de incidencias</h2>*@
<br />
<div class="tab-content">
    @Html.ActionLink("   Reportar", "Create", null, new { @class = "btn btn-primary btn-large col-md-12 far fa-plus-square actionLinkReportar" })
</div><br />

<table id="incidencias" class="table table-striped">
    <thead>

    </thead>
    <tbody></tbody>
</table>



@section scripts{
    <script>

        $(document).ready(function () {

            $("#incidencias").DataTable({

                //Definiendo valores default de la tabla
                "order": [[0, "desc"]],
                "searching": true,
                'responsive': true,
                "processing": true,
                'language': {
                    url: '../Content/DataTables/TraductorDataTable.json' //Ubicacion del archivo con el json del idioma.
                },

                //Obtener incidencias
                ajax: {
                    url: "..SemmDesk/incidencias/getincidencias",
                    dataSrc: ""
                },

                //CallBack para colores en el estado de las incidencias
                "createdRow": function (row, data, index) {

                    if (data.Estado == 'Abierta') {
                        $('td', row).eq(7).addClass('EstadoAbiertas');
                    }

                    if (data.Estado == 'Cerrada') {
                        $('td', row).eq(7).addClass('EstadoCerradas');
                    }

                    if (data.Estado == 'Reasignada') {
                        $('td', row).eq(7).addClass('EstadoReasignadas');
                    }

                    if (data.Estado == 'Urgentes') {
                        $('td', row).eq(7).addClass('EstadoUrgentes');
                    }

                    if (data.Estado == 'Retrasada') {
                        $('td', row).eq(7).addClass('EstadoUrgentes');
                    }
                },

                //Creando las columnas de la tabla
                columns: [
                    {
                        title: "ID",
                        data: "ID"
                    },
                    {
                        title: 'Fecha',
                        data: 'Fecha', 'render': function (date) {
                            var date = new Date(parseInt(date.substr(6)));
                            //var month = date.getMonth() + 1;
                            var time = date.toLocaleString().toString("dd/MM/yyy HH:MM");
                            timeR = time - Date.now;
                            if (timeR > 3) {
                                $('td', row).eq(7).addClass('EstadoUrgentes');
                            }
                            return time;
                        }

                    },
                    {
                        title: "Categoría",
                        data: "Categoria"
                    },
                    {
                        title: "Sub-Categoría",
                        data: "SubCategoria"
                    },
                    {
                        title: "Departamento",
                        data: "Departamento"
                    },
                    {
                        title: "Usuario",
                        data: "Usuario"
                    },
                    {
                        title: "Detalle",
                        data: "Detalle"
                    },
                   
                    {
                        title: "Estado",
                        data: "Estado"
                    },
                    {
                        data: "ID",
                        render: function (data, type, ID) {
                            return "<a href='..SemmDesk/incidencias/Details/ " + data + "'><i class='far fa-eye'></i></a>";
                        }
                    },
                    //{
                    //    data: "Id",
                    //    render: function (data) {
                    //        return "<button class='btn-link js-edit' incidencia-id =" + data + ">Trabajar <i class='far fa-edit'></i></i></button>";
                    //    }
                    //}
                ]
            });           

        });

    </script>
}

SemmDesk/Views/Incidencias/Salir.cshtml
@{
    ViewBag.Title = "Salir";
}

<h2>Salir</h2>